# -*- coding: utf-8 -*-
"""EDA churn and customer spend

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSeWwptDhtQcMu30ssg58xaj1aO6mhQm
"""

#code snippet 1
#inserting data from the url to initiate analisys process
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/Imjuandiaz/churn-data/refs/heads/main/WA_Fn-UseC_-Telco-Customer-Churn.csv")

df

#code snippet 2
#displaying data columns and data types
df.info()
df.columns

#code snippet 3
#Displaying statistical analysis on the dataframe
df.describe()

#code snippet 4
#importing misingno for data proportion analysis avoiding featuring with more then 20% missing values
import missingno as msno
msno.bar(df)

#code snippet 5
#importing significant correlation package dython
!pip install dython

#code snippet 6
#importing dython for correlation analysis
import dython
from dython.nominal import associations
assoc = associations(df)

#code snippet 7
# Storing the correlations in a matrix
assoc_matrix = assoc['corr']

#code snippet 8
#Setting the target variable Churn
target = 'Churn'

# List the associated variables in the descending order of influence on the target variable
assoc_matrix[target].abs().sort_values(ascending=False)

#code snippet 10
#Setting the target variable MonthlyCharges
target = 'MonthlyCharges'

# List the associated variables in the descending order of influence on the target variable
assoc_matrix[target].abs().sort_values(ascending=False)

#code snippet 11
# Installing ydata profiling package for detailed data profiling (Exploratory Data Analysis, EDA)
!pip install -U ydata-profiling

#code snippet 12
#installing ydata profiling package for detailed data profiling
from ydata_profiling import ProfileReport
profile = ProfileReport(df)
profile.to_file(output_file='Churn_Spend_Telco_Customers2025.html')

#code snippet 13
# Installing AutoViz package for auto visualizations
!pip install autoviz

# Importing Autoviz modules
from autoviz.AutoViz_Class import AutoViz_Class


# Starting the Autoviz instance
AV = AutoViz_Class()




# Generating visuals using AutoViz modules
AV.AutoViz(df, verbose = 2, depVar= 'Churn')

#code snippet 14
# Starting the Autoviz instance
AV = AutoViz_Class()




# Generating visuals using AutoViz modules
AV.AutoViz(df, verbose = 2, depVar= 'MonthlyCharges')